package com.cloudbees.eclipse.dev.ui;

public interface CBImages {

  String IMG_REFRESH = "IMG_REFRESH";
  String IMG_GLOBE = "IMG_GLOBE";
  String IMG_CONSOLE = "IMG_CONSOLE";
  String IMG_FOLDER_HOSTED = "IMG_FOLDER_HOSTED";
  String IMG_FOLDER_LOCAL = "IMG_FOLDER_LOCAL";
  String IMG_INSTANCE = "IMG_INSTANCE";
  String IMG_VIEW = "IMG_VIEW";

  String IMG_FILE = "IMG_FILE";
  String IMG_FILE_ADDED = "IMG_FILE_ADDED";
  String IMG_FILE_DELETED = "IMG_FILE_DELETED";
  String IMG_FILE_MODIFIED = "IMG_FILE_MODIFIED";

  String IMG_BROWSER = "IMG_BROWSER";
  String IMG_RUN = "IMG_RUN";

  String IMG_COLOR_PREFIX = "IMG_COLOR_";

  String IMG_16 = "16_";
  String IMG_24 = "24_";

  String IMG_COLOR_16_GREY = IMG_COLOR_PREFIX + "16_GREY";
  String IMG_COLOR_16_RED = IMG_COLOR_PREFIX + "16_RED";
  String IMG_COLOR_16_BLUE = IMG_COLOR_PREFIX + "16_BLUE";

  String IMG_COLOR_24_RED = IMG_COLOR_PREFIX + "24_RED";
  String IMG_COLOR_24_BLUE = IMG_COLOR_PREFIX + "24_BLUE";

  String IMG_HEALTH_PREFIX = "IMG_HEALTH_";

  String IMG_HEALTH_16_00_to_19 = IMG_HEALTH_PREFIX + IMG_16 + "health-00to19.gif";
  String IMG_HEALTH_16_20_to_39 = IMG_HEALTH_PREFIX + IMG_16 + "health-20to39.gif";
  String IMG_HEALTH_16_40_to_59 = IMG_HEALTH_PREFIX + IMG_16 + "health-40to59.gif";
  String IMG_HEALTH_16_60_to_79 = IMG_HEALTH_PREFIX + IMG_16 + "health-60to79.gif";
  String IMG_HEALTH_16_80PLUS = IMG_HEALTH_PREFIX + IMG_16 + "health-80plus.gif";

  String IMG_HEALTH_24_00_to_19 = IMG_HEALTH_PREFIX + IMG_24 + "health-00to19.gif";
  String IMG_HEALTH_24_20_to_39 = IMG_HEALTH_PREFIX + IMG_24 + "health-20to39.gif";
  String IMG_HEALTH_24_40_to_59 = IMG_HEALTH_PREFIX + IMG_24 + "health-40to59.gif";
  String IMG_HEALTH_24_60_to_79 = IMG_HEALTH_PREFIX + IMG_24 + "health-60to79.gif";
  String IMG_HEALTH_24_80PLUS = IMG_HEALTH_PREFIX + IMG_24 + "health-80plus.gif";

  String IMG_JUNIT = "IMG_JUNIT";

  String IMG_BUILD_DETAILS = "IMG_BUILD_DETAILS";

  String IMG_DELETE = "IMG_DELETE";
  String IMG_DELETE_DISABLED = "IMG_DELETE_DISABLED";

}
