#!/bin/bash
#CloudBees SDK
if [ "$BEES_HOME" == "" ]
then
 BEES_HOME=$STAX_HOME
fi
if [ "$BEES_HOME" == "" ]
then
 echo BEES_HOME is not set
 exit 2
fi
export STAX_HOME=$BEES_HOME

export JAVA_OPTS="-Dbees.home=$BEES_HOME -Xmx256m $BEES_OPTS"
java $JAVA_OPTS -cp $BEES_HOME/lib/cloudbees-boot.jar com.cloudbees.sdk.boot.Launcher "$@"

